### ISSUE TITLE
Does not support the "Fast Charge" and "USB Fast Charge"？

### ISSUE THREAD

**Issue by Aloento** [showp1984/bricked-hammerhead#6]
Does not support the "Fast Charge" and "USB Fast Charge"？
A 5.3+V 2A
Actual：5.48V 0.8A
USB：5.17V 0.4A

**Comment by showp1984** [comment]
I'm unsure what you want to tell me with this. Could you try to explain your issue better?

**Comment by Aloento** [comment]
It does not support USB fast charging.

**Comment by showp1984** [comment]
Nope it doesn't. It won't either. USB 2.0 specification states 500mA maximum current flow. Under best conditions USB 2.0 will deliver that, usually you will see +/- 5% of that.
If your USB controller / motherboard is built to specifications it will limit the current anyway in a polyfuse way: you pull 700mA for a short time and the USB controller will limit the current to nearly zero. In effect your phone will charge faster for a very short time and then not charge at all for some time. You will gain nothing.
If your USB controller / motherboard is NOT built to specifications it will NOT limit the current, sadly this is present on a lot of cheap boards. This will, sooner or later blow your USB controller and/or motherboard.

Assessment: RISK > GAIN
State: Will not implement. Closed.

(You can patch it in yourself though and recompile)
